<script lang="ts">
  import { page } from '$app/stores';
  import { api } from '$lib/api';

  let journey = $state<any>(null);
  let loading = $state(true);

  $effect(() => {
    const id = $page.params.id;
    if (id) loadJourney(id);
  });

  async function loadJourney(id: string) {
    try {
      const res = await api.get(`/journeys/${id}`);
      journey = res.data;
    } catch (err) {
      console.error('Failed to load journey:', err);
    } finally {
      loading = false;
    }
  }
</script>

<div>
  {#if loading}
    <div class="flex items-center justify-center py-24">
      <div class="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent"></div>
    </div>
  {:else if journey}
    <div class="mb-6">
      <a href="/" class="text-sm text-text-muted hover:text-primary">← Back to Dashboard</a>
    </div>
    <h1 class="mb-2 text-3xl font-bold text-text">{journey.title || 'Journey'}</h1>
    <p class="mb-8 text-text-muted">
      Level: {journey.level || 'TBD'} · Status: {journey.status}
    </p>

    <div class="rounded-xl bg-surface p-6 shadow-sm ring-1 ring-border">
      <h2 class="mb-4 text-xl font-semibold text-text">Steps</h2>
      <p class="text-text-muted">
        Steps will be generated by the AI personalization engine based on your profile and comfort level.
      </p>
    </div>
  {:else}
    <p class="text-text-muted">Journey not found.</p>
  {/if}
</div>
