/** A true/false specification question generated by the LLM */
export interface PlannerQuestion {
	id: number;
	question: string;
}

/** An answered specification question */
export interface PlannerAnswer {
	id: number;
	question: string;
	answer: boolean;
}

/** The final AI usage strategy produced by the planner */
export interface PlannerStrategy {
	title: string;
	summary: string;
	steps: PlannerStrategyStep[];
	examplePrompt: string;
	recommendedTools: PlannerTool[];
	tips: string[];
}

export interface PlannerStrategyStep {
	order: number;
	title: string;
	description: string;
	aiRole: string;
}

export interface PlannerTool {
	name: string;
	description: string;
	url?: string;
}

/** Round number: 1, 2, or 3 */
export type PlannerRound = 1 | 2 | 3;
