/** A true/false specification question generated by the LLM */
export interface PlannerQuestion {
	id: number;
	question: string;
}

/** An answered specification question */
export interface PlannerAnswer {
	id: number;
	question: string;
	answer: boolean;
	context?: string;
}

/** The final AI usage strategy produced by the planner */
export interface PlannerStrategy {
	title: string;
	summary: string;
	startingState: string;
	endResult: string;
	nextSteps: string;
	steps: PlannerStrategyStep[];
	tool: "chatgpt";
}

export interface PlannerStrategyStep {
	order: number;
	title: string;
	description: string;
	inputArtifacts: string;
	outputArtifacts: string;
	prompt: string;
}

/** Round number: 1, 2, or 3 */
export type PlannerRound = 1 | 2 | 3;
